import type { CameraPresetId, CameraConfig } from './types';

export const CAMERA_PRESETS: Record<CameraPresetId, CameraConfig> = {
  'orbit-default': {
    position: [0, 2, 5],
    target: [0, 0, 0],
    fov: 50,
    near: 0.1,
    far: 100,
    controlsType: 'orbit',
    damping: 0.05,
    autoRotate: false,
  },
  'orbit-close': {
    position: [0, 1, 3],
    target: [0, 0, 0],
    fov: 45,
    near: 0.1,
    far: 100,
    controlsType: 'orbit',
    damping: 0.05,
    autoRotate: false,
  },
  'orbit-far': {
    position: [0, 4, 10],
    target: [0, 0, 0],
    fov: 55,
    near: 0.1,
    far: 100,
    controlsType: 'orbit',
    damping: 0.05,
    autoRotate: false,
  },
  'fixed-front': {
    position: [0, 0, 5],
    target: [0, 0, 0],
    fov: 50,
    near: 0.1,
    far: 100,
    controlsType: 'fixed',
    damping: 0,
    autoRotate: false,
  },
  'fixed-angle': {
    position: [3, 3, 5],
    target: [0, 0, 0],
    fov: 50,
    near: 0.1,
    far: 100,
    controlsType: 'fixed',
    damping: 0,
    autoRotate: false,
  },
  'fixed-top': {
    position: [0, 8, 2],
    target: [0, 0, 0],
    fov: 50,
    near: 0.1,
    far: 100,
    controlsType: 'fixed',
    damping: 0,
    autoRotate: false,
  },
  'scroll-dolly': {
    position: [0, 2, 8],
    target: [0, 0, 0],
    fov: 50,
    near: 0.1,
    far: 100,
    controlsType: 'scroll',
    damping: 0.1,
    autoRotate: false,
  },
  'scroll-pan': {
    position: [0, 2, 5],
    target: [0, 0, 0],
    fov: 50,
    near: 0.1,
    far: 100,
    controlsType: 'scroll',
    damping: 0,
    autoRotate: false,
  },
  'scroll-orbit': {
    position: [3, 2, 5],
    target: [0, 0, 0],
    fov: 50,
    near: 0.1,
    far: 100,
    controlsType: 'scroll',
    damping: 0,
    autoRotate: true,
    autoRotateSpeed: 0.5,
  },
};
