import type { MaterialPresetId, MaterialConfig } from './types';

export const MATERIAL_PRESETS: Record<MaterialPresetId, MaterialConfig> = {
  default: {
    type: 'MeshStandardMaterial',
    color: '#6366f1',
    metalness: 0.3,
    roughness: 0.5,
    opacity: 1,
    transparent: false,
    envMapIntensity: 1,
    wireframe: false,
  },
  glass: {
    type: 'MeshPhysicalMaterial',
    color: '#88ccff',
    metalness: 0,
    roughness: 0,
    opacity: 0.3,
    transparent: true,
    envMapIntensity: 1.5,
    wireframe: false,
  },
  metal: {
    type: 'MeshStandardMaterial',
    color: '#c0c0c0',
    metalness: 0.9,
    roughness: 0.1,
    opacity: 1,
    transparent: false,
    envMapIntensity: 1,
    wireframe: false,
  },
  plastic: {
    type: 'MeshStandardMaterial',
    color: '#ff6b6b',
    metalness: 0,
    roughness: 0.6,
    opacity: 1,
    transparent: false,
    envMapIntensity: 1,
    wireframe: false,
  },
  holographic: {
    type: 'MeshPhysicalMaterial',
    color: '#a855f7',
    metalness: 0.5,
    roughness: 0.1,
    opacity: 1,
    transparent: false,
    envMapIntensity: 2.0,
    wireframe: false,
    shaderUniforms: {
      iridescence: { value: 1.0 },
    },
  },
  wireframe: {
    type: 'MeshBasicMaterial',
    color: '#22d3ee',
    metalness: 0,
    roughness: 0,
    opacity: 1,
    transparent: false,
    envMapIntensity: 0,
    wireframe: true,
  },
  gradient: {
    type: 'MeshStandardMaterial',
    color: '#818cf8',
    metalness: 0.2,
    roughness: 0.4,
    opacity: 1,
    transparent: false,
    envMapIntensity: 1,
    wireframe: false,
  },
  fresnel: {
    type: 'MeshPhysicalMaterial',
    color: '#06b6d4',
    metalness: 0.1,
    roughness: 0.2,
    opacity: 1,
    transparent: false,
    envMapIntensity: 1,
    wireframe: false,
    shaderUniforms: {
      fresnelPower: { value: 2.0 },
    },
  },
  matcap: {
    type: 'MeshBasicMaterial',
    color: '#f59e0b',
    metalness: 0,
    roughness: 0,
    opacity: 1,
    transparent: false,
    envMapIntensity: 0,
    wireframe: false,
  },
};
